modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/SaltSouls/Packed-Up"
logoFile = "logo.png"
logoBlur = false
authors="${mod_authors}"
credits="${mod_credits}"
description='''${mod_description}'''
itemIcon = "packedup:cobblestone_crate"
configBackground = "minecraft:textures/block/spruce_planks.png"

[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="farmersdelight"
   mandatory=true
   versionRange="${fd_version_range}"
   ordering="BEFORE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="supplementaries"
   mandatory=false
   versionRange="${sup_version_range}"
   ordering="BEFORE"
   side="BOTH"
